/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Admin: () => import('#controllers/admin_controller'),
  Analytics: () => import('#controllers/analytics_controller'),
  BotSimulations: () => import('#controllers/bot_simulations_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Health: () => import('#controllers/health_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Quotes: () => import('#controllers/quotes_controller'),
  Tags: () => import('#controllers/tags_controller'),
  Users: () => import('#controllers/users_controller'),
}
