envGroups:
  - name: quoteshub-env
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_APP_KEY
        sync: false
      - key: PUSHER_APP_SECRET
        sync: false
      - key: PUSHER_APP_CLUSTER
        sync: false

services:
  - type: web
    name: quoteshub-web
    env: php
    plan: free
    buildCommand: "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run build"
    preDeployCommand: "php artisan migrate --force"
    customDomains:
      - thequoteshub.info
      - www.thequoteshub.info
    envGroups:
      - quoteshub-env

  - type: cron
    name: quoteshub-queue-cron
    env: php
    plan: free
    schedule: "* * * * *"
    buildCommand: "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader"
    startCommand: "php artisan queue:work --stop-when-empty --timeout=90 --tries=3"
    envGroups:
      - quoteshub-env
